[env:nodemcu-32s]
platform = espressif32
board = nodemcu-32s
framework = arduino
board_build.partitions = partitions_custom.csv
board_build.flash_mode = dio
monitor_speed = 115200
lib_deps =
    me-no-dev/ESPAsyncWebServer @ 3.6.0
    ESP32Async/AsyncTCP @ 3.1.1
    bblanchon/ArduinoJson @ 7.4.3
    lorol/LittleFS_esp32 @ 1.0.6
    armmbed/mbedtls @ 2.23.0
build_flags =
    -DCORE_DEBUG_LEVEL=0
    -DCONFIG_ARDUINO_LOOP_STACK_SIZE=8192
    -Wno-unused-variable
    -Wno-unused-function
