[env:nodemcu-32s]
platform = espressif32
board = nodemcu-32s
platform_packages =
    toolchain-xtensa-esp32 @ file:///data/data/com.termux/files/home/.platformio/packages/toolchain-xtensa-esp32/8.4.0+2021r2-patch5
    tool-esptoolpy @ file:///data/data/com.termux/files/home/.platformio/packages/tool-esptoolpy/dummy
framework = arduino
board_build.partitions = partitions_custom.csv
board_build.flash_mode = dio
monitor_speed = 115200
lib_deps =
    ESPAsyncWebServer
    AsyncTCP
    ArduinoJson
    LittleFS_esp32
    mbedtls
build_flags =
    -DCORE_DEBUG_LEVEL=0
    -DCONFIG_ARDUINO_LOOP_STACK_SIZE=8192
    -Wno-unused-variable
    -Wno-unused-function
